-- ============================================================
-- FIX BY EMAIL — Finds user by email and approves that account
-- ============================================================

-- STEP 1: Find the actual user ID for sunny.sobhani90@gmail.com
SELECT id, email, created_at 
FROM auth.users 
WHERE email = 'sunny.sobhani90@gmail.com';

-- STEP 2: After seeing the UUID above, replace YOUR_UUID_HERE and uncomment:
-- 
-- DO $$
-- DECLARE
--   v_user_id UUID := 'YOUR_UUID_HERE';  -- <-- REPLACE THIS
--   v_profiles_cols TEXT[];
--   v_user_roles_cols TEXT[];
--   v_insert_cols TEXT;
--   v_values TEXT;
--   v_update_set TEXT;
-- BEGIN
--   -- Get actual columns in profiles
--   SELECT array_agg(column_name) INTO v_profiles_cols
--   FROM information_schema.columns 
--   WHERE table_schema = 'public' AND table_name = 'profiles';
--   
--   -- Build dynamic INSERT for profiles
--   v_insert_cols := 'id';
--   v_values := quote_literal(v_user_id);
--   v_update_set := '';
--   
--   IF 'full_name' = ANY(v_profiles_cols) THEN
--     v_insert_cols := v_insert_cols || ', full_name';
--     v_values := v_values || ', ' || quote_literal('sunny.sobhani90@gmail.com');
--   END IF;
--   
--   IF 'approval_status' = ANY(v_profiles_cols) THEN
--     v_insert_cols := v_insert_cols || ', approval_status';
--     v_values := v_values || ', ' || quote_literal('approved');
--     v_update_set := v_update_set || 'approval_status = ' || quote_literal('approved') || ', ';
--   END IF;
--   
--   IF 'approved_at' = ANY(v_profiles_cols) THEN
--     v_insert_cols := v_insert_cols || ', approved_at';
--     v_values := v_values || ', now()';
--     v_update_set := v_update_set || 'approved_at = now(), ';
--   END IF;
--   
--   IF 'created_at' = ANY(v_profiles_cols) THEN
--     v_insert_cols := v_insert_cols || ', created_at';
--     v_values := v_values || ', now()';
--   END IF;
--   
--   IF length(v_update_set) > 0 THEN
--     v_update_set := left(v_update_set, length(v_update_set) - 2);
--   ELSE
--     v_update_set := 'id = id';
--   END IF;
--   
--   EXECUTE format(
--     'INSERT INTO public.profiles (%s) VALUES (%s) ON CONFLICT (id) DO UPDATE SET %s',
--     v_insert_cols, v_values, v_update_set
--   );
--   
--   -- Add admin role
--   INSERT INTO public.user_roles (user_id, role) 
--   VALUES (v_user_id, 'admin') 
--   ON CONFLICT DO NOTHING;
--   
--   RAISE NOTICE 'User % has been approved and given admin role', v_user_id;
-- END $$;

-- STEP 3: Uncomment and run this after step 2 to verify:
-- SELECT 
--   public.has_role('YOUR_UUID_HERE'::uuid, 'admin') as has_admin,
--   public.is_approved('YOUR_UUID_HERE'::uuid) as is_approved;
