// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const supabaseConfigError =
  !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY
    ? 'Missing Supabase environment variables. Ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set in .env'
    : null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const fallbackUrl = 'https://placeholder.supabase.co';
const fallbackKey = 'placeholder-publishable-key';

export const supabase = createClient<Database>(SUPABASE_URL || fallbackUrl, SUPABASE_PUBLISHABLE_KEY || fallbackKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
